---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-recommender
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-recommender
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      containers:
      - name: recommender
        image: k8s.gcr.io/vpa-recommender:0.6.3
        command:
        - /recommender
        args:
        - --stderrthreshold=info
        - --v=2
        - --storage=prometheus
        - --prometheus-address=http://prometheus-server
        - --pod-recommendation-min-cpu-millicores=10
        - --pod-recommendation-min-memory-mb=30
        - --kube-api-qps=200
        - --kube-api-burst=200
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - containerPort: 8080
