{
 "title": "Scaling Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "vpa",
    "query": "label_values(kube_verticalpodautoscaler_spec_updatepolicy_updatemode, target_name)"
   },
   {
    "name": "hpa",
    "query": "label_values(kube_hpa_status_condition, hpa)"
   }
  ]
 },
 "panels": [
  { "title": "Vertical Scaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VPA Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_verticalpodautoscaler_spec_updatepolicy_updatemode{target_name=\"$vpa\", update_mode=\"Auto\"}==1"
    }
   ]
  },
  {
   "title": "Resources for $vpa",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_upperbound{target_name=\"$vpa\", unit=\"core\"}",
     "legendFormat": "Upper"
    },
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{target_name=\"$vpa\", unit=\"core\"}",
     "legendFormat": "Target"
    },
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_lowerbound{target_name=\"$vpa\",unit=\"core\"}",
     "legendFormat": "Lower"
    },
    {
     "expr": "sum by(pod_name) (irate(container_cpu_usage_seconds_total{container_name=~\"$vpa\"}[1m]))",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{container=\"$vpa\"})",
     "legendFormat": "Request"
    }
   ]
  },
  { "title": "Horizontal Scaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "HPA Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kube_hpa_status_condition{hpa=\"$hpa\", condition=\"ScalingActive\"}==1"
    }
   ]
  },
  {
   "title": "Resources for $hpa",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 2, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (irate(container_cpu_usage_seconds_total{container_name=~\"$hpa\"}[1m]))",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{container_name=\"$hpa\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "kube_hpa_status_current_metrics_average_value{hpa=\"$hpa\"}",
     "legendFormat": "HPA Metrics"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{container=\"$hpa\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Replicas for $hpa",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_hpa_spec_max_replicas{hpa=\"$hpa\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "kube_hpa_spec_min_replicas{hpa=\"$hpa\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "kube_hpa_status_current_replicas{hpa=\"$hpa\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "kube_hpa_status_desired_replicas{hpa=\"$hpa\"}",
     "legendFormat": "Desired"
    }
   ]
  }
 ]
}