apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: evns/sqrt-client:1
        imagePullPolicy: Always
        name: client
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
      restartPolicy: Always
