apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hserver
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hserver
  targetCPUUtilizationPercentage: 75
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hserver
  labels:
    app: hserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hserver
    spec:
      containers:
      - image: evns/sqrt-server
        imagePullPolicy: Always
        name: hserver
        resources:
          requests:
            cpu: 100m
            memory: 10Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hserver
spec:
  selector:
    app: hserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080    

      